# This is a template batch script to run a Matlab serial job under SGE in 
# the UCL CS cluster.
# ------------------------------------------------------------------------
# Please DO NOT EDIT THIS FILE, but create a similar file for your own
# analysis (e.g. jobs.sh) and move it to the toolkit folder. Then you
# can run it as:
# qsub jobs.sh <matlab script>
#
# NB matlab script should have no extension
# ------------------------------------------------------------------------

# 1. Force bash as the executing shell.
#$ -S /bin/bash

# 2. Request hours of wallclock time (format hours:minutes:seconds).
#$ -l h_rt=1:0:0

# 3. Request 7.5 gigabytes of RAM.
#$ -l h_vmem=7.5G,tmem=7.5G

# 4. Set up the job array. In this instance we have requested 200 tasks
# numbered 1 to 200.
#$ -t 1-200

# 5. Set the name of the job.
#$ -N runMain

# 6. Have standard out and standard error merged into one file.
#$ -j y

# 7. Set the working directory. Use -cwd to set the current working directory or
#$ -cwd

# 8. Run the application.
/usr/local/matlab/bin/matlab -nodisplay -nodesktop -nojvm -nosplash -singleCompThread -r  "$*" 
