#!/bin/bash

# This is a template batch script to run a Matlab serial job under SLURM in 
# the cluster.
# ------------------------------------------------------------------------
# Please DO NOT EDIT THIS FILE, but create a similar file for your own
# analysis (e.g. jobs.sh) and move it to the main toolkit folder. Then you
# can run it as:
# qsub jobs.sh <matlab script>
#
# NB matlab script should have no extension
# ---------------------------------------------------
#  for more information on SLURM scheduling visit
#  https://slurm.schedmd.com/documentation.html 

# 1. Define a job name
#SBATCH --job-name=pls-cca

# 2. Define a name and location for your log files
#SBATCH --output=log_%a.out

# 3. Specify computational resources 
#    name of the partition will depend on your cluster
#SBATCH --partition express
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --mem-per-cpu=2G
#SBATCH --time=0-02:00:00

# 4. Specify the number of jobs to run (should be in an array)
# SBATCH --array=1-100%20

# 5. Activate matlab - this will be different for every cluster 
# activate matlab module
module add matlab/R2019b

# 6. change working directory to toolbox folder
#    you don't need to do this is this file is still within the toolbox folder
cd /PATH/TO/PLS_CCA_framework/

# 7. finally run the script
matlab -nodisplay -nodesktop -nojvm -nosplash -singleCompThread -r "addpath('$1'); $2"

